### ISSUE TITLE
Plug安装问题请教！---fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by PerryShen** [BoyPao/cace#1]
![3dba522c7266ba05d58110f386228cc](https://github.com/BoyPao/cace/assets/40953652/96df07bc-6a22-400b-b0d9-dd7888eaa92d)
我的其他的插件都没有问题，只有这个插件有问题，麻烦check一下是插件的问题，还是我的问题。我在网上搜了一下，有的让配置个人信息，但是我认为HTTPs下载不需要配置个人信息。我的其他的插件都没有问题。

**Comment by BoyPao** [comment]
你好，请提供你的插件管理器名称以及cace在其中的配置信息

**Comment by BoyPao** [comment]
你好，你的问题可能是拼写错误。
请尝试使用正确的拼写: coce -> cace。
我使用git clone或是vim-plug都可以正常下载以及更新。详情请参考README.md
因此我将resloved这个issue。如果上述方法不能解决你的问题，请提供你使用的插件管理器名称以及cace相关配置，并reopen这个issue。

**Comment by PerryShen** [comment]
是我自己写错了，经试验可以正常安装并使用，大佬牛逼！
